const actionTypes = {
  REST_SUCCESS: "REST_SUCCESS",
  REST_ERROR: "REST_ERROR",
  REST_LOAD: "REST_LOADING",
  CART_SUCCESS: "CART_SUCCESS",
  CART_ERROR: "CART_ERROR",
  CART_LOAD: "CART_LOADING",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
  DELETE_CART_ITEM: "DELETE_CART_ITEM",
};
export default actionTypes;
